name: "Setup GitHub Settings"
description: "Sets up CODEOWNERS and applies branch protection rules."
runs:
  using: "composite"


    - name: Apply Branch Protection
      run: python apply_branch_protection.py
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
        REPO_OWNER: ${{ github.repository_owner }}
        REPO_NAME: ${{ github.event.repository.name }}
        BRANCH_NAME: "main"  # Default branch
