name: Apply GitHub Settings and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  block_direct_pushes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: pip install requests
      
      - name: Block direct pushes to main
        run: python block_direct_pushes.py
        env:
          TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}
          REPO_OWNER: ${{ secrets.REPO_OWNER }}
          REPO_NAME: ${{ secrets.REPO_NAME }}
          DEPLOY_BRANCH: ${{ secrets.DEPLOY_BRANCH }}

  set_pr_approvals:
    runs-on: ubuntu-latest
    needs: block_direct_pushes
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: pip install requests
      
      - name: Set PR approvals from Ravi and Manasa
        run: python set_pr_approvals.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}

  deploy_to_production:
    runs-on: ubuntu-latest
    needs: set_pr_approvals
    if: github.ref == 'refs/heads/main'  # Ensure this only runs on `main`
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python (or any other environment)
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run tests (optional)
        run: |
          # Run your tests here before deployment
          pytest

      - name: Deploy to Production
        run: |
          # Add deployment commands for production
          echo "Deploying to production..."
          # Example: aws deploy, gcloud deploy, az webapp up
