name: Apply Branch Protection

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  env:
  BRANCH: main  # Define the branch variable globally as 'main'

  protect_branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Apply branch protection
        run: python set_branch_protection.py
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}  # GitHub-provided token with repo permissions
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
          BRANCH: ${{ env.BRANCH }}  # Use the branch defined globally