name: Ensure Branch Protection

on:
  pull_request:
    branches:
      - main
      - '*'  # Apply for any branch

jobs:
  enforce-branch-protection:
    runs-on: ubuntu-latest

    steps:
      - name: Ensure Branch Protection Rules
        run: |
          # Use GitHub API to set branch protection rules for the main branch
          curl -X PUT \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN}}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/branches/${{ github.event.pull_request.base.ref }}/protection" \
            -d '{
              "required_status_checks": {
                "strict": true,
                "contexts": []
              },
              "enforce_admins": true,
              "required_pull_request_reviews": {
                "required_approving_review_count": 2,
                "dismiss_stale_reviews": true,
                "require_code_owner_reviews": true
              },
              "restrictions": null
            }'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
