name: Branch Protection Setup

on:
  push:
    branches:
      - main

jobs:
  branch_protection:
    runs-on: ubuntu-latest
    steps:
      - name: Set up branch protection for main branch
        run: |
          curl -X PUT -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.luke-cage-preview+json" \
          https://api.github.com/repos/${{ github.repository }}/branches/main/protection \
          -d '{
              "required_status_checks": {
                "strict": true,
                "contexts": []
              },
              "enforce_admins": true,
              "required_pull_request_reviews": {
                "dismiss_stale_reviews": true,
                "require_code_owner_reviews": true,
                "required_approving_review_count": 1
              },
              "restrictions": null
          }'
