name: Ensure Branch Protection

on:
  pull_request:
    branches:
      - main
      - '*'  # Apply for any branch

jobs:
  enforce-branch-protection:
    runs-on: ubuntu-latest

    steps:
      - name: Set Branch Protection Rules via GitHub API
        run: |
          # Define the branch to set the protection rules
          BRANCH_NAME="main"

          # Use the GitHub API to set branch protection rules
          curl -X PUT \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.luke-cage-preview+json" \
            "https://api.github.com/repos/${{ github.repository }}/branches/$BRANCH_NAME/protection" \
            -d '{
              "required_status_checks": {
                "strict": true,
                "contexts": []
              },
              "enforce_admins": true,
              "required_pull_request_reviews": {
                "required_approving_review_count": 2,
                "dismiss_stale_reviews": true,
                "require_code_owner_reviews": true
              },
              "restrictions": null
            }'

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}