name: Enforce Branch Protection and Deployment Rules

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  branch_protection:
    name: Set Branch Protection Rules
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Apply branch protection rules
      run: |
        python apply_branch_protection.py
      env:
        TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}
        REPO_OWNER: ${{ secrets.REPO_OWNER }}
        REPO_NAME: ${{ secrets.REPO_NAME }}
        DEPLOY_BRANCH: ${{ secrets.DEPLOY_BRANCH }}

#  check_deploy_branch:
 #   name: Restrict Production Deployments
  #  runs-on: ubuntu-latest
   # if: github.ref != 'refs/heads/main'  # Ensure this job only runs if not on main branch

    #steps:
#    - name: Fail if not deploying from main
 #     run: |
  #      echo "Deployments are only allowed from the main branch."
   #     exit 1
