name: Update Branch Protection Settings

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  update-protection:
    runs-on: ubuntu-latest

    steps:
      - name: Update Branch Protection Rules
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}  # Your PAT secret
        run: |
          echo "Updating branch protection rules for the main branch..."

          # Set branch protection rules using the GitHub API
          curl -X PUT \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/branches/main/protection \
            -d '{
              "required_status_checks": null,
              "enforce_admins": true,
              "required_pull_request_reviews": {
                "required_approving_review_count": 1,
                "dismiss_stale_reviews": true
              },
              "restrictions": null,
              "allow_force_pushes": false,
              "allow_deletions": false
            }'

          echo "Branch protection rules updated successfully!"
