name: Deploy to Production

on:
  push:
    branches:
      - main  # Trigger deployment only on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'  # Ensure that the workflow only runs on the main branch

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to Production
        run: |
          echo "Deploying to production from the main branch..."
