name: Deploy to Production

on:
  push:
    branches:
      - main  # Only trigger on pushes to main

jobs:
  deploy-prod:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Production
        run: |
          echo "Deploying to production from the main branch"
