name: Test Deployment
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}'
          
      - name: Install gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'  

      - name: Authenticate with GKE
        run: |
          gcloud container clusters get-credentials lab-datahub2-01-ne1-warpstream-clstr \
          --region northamerica-northeast1 \
          --project ti-ds-tii-01
      - name: Get pod details
        run: |
          kubectl get pods -n warpstream
