name: Deploy to Production

on:
  push:
    branches:
      - main  # Restrict deployment to main branch only

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'  # This ensures the job only runs on the main branch
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Production
        run: |
          echo "Deploying to production..."
