name: Check PR Approval from Code Owners

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]

jobs:
  check-codeowners-approval:
    runs-on: ubuntu-latest

    steps:
      # Step to checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step to check PR approvals from CODEOWNERS
      - name: Check PR Code Owners Approval
        uses: actions/github-script@v5
        with:
          script: |
            const prNumber = context.payload.pull_request.number;

            // Fetch the reviews for the pull request
            const reviews = await github.rest.pulls.listReviews({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber,
            });

            // Fetch the CODEOWNERS file content
            const codeownersContent = await github.rest.repos.getContent({
              owner: context.repo.owner,
              repo: context.repo.repo,
              path: '.github/CODEOWNERS',
            });

            // Check for approved reviews by code owners
            const approvedReviews = reviews.data.filter(review => review.state === 'APPROVED');
            const codeOwnerApprovals = approvedReviews.filter(review => codeowners.includes(review.user.login));

            console.log(`PR #${prNumber} has ${codeOwnerApprovals.length} approval(s) from code owners.`);
            console.log(`Required approvals from code owners: ${codeowners.join(', ')}`);

            // Require at least one approval from code owners
            if (codeOwnerApprovals.length === 0) {
              throw new Error(`This PR needs at least one approval from a code owner: ${codeowners.join(', ')}`);
            }
            console.log('Code owner approval check passed.');
