name: Check PR Approval from Codeowners

on:
  pull_request_review:
    types: [submitted]

jobs:
  check-approval:
    runs-on: ubuntu-latest

    steps:
      - name: Check PR Approval Status
        uses: actions/github-script@v5
        with:
          script: |
            const prNumber = context.payload.pull_request.number;

            // Fetch all reviews for the pull request
            const reviews = await github.pulls.listReviews({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber,
            });

            // Check if any code owners have approved
            const approvals = reviews.data.filter(review => review.state === 'APPROVED' && review.user.login === 'code-owner-username');

            // Output the current approval status
            console.log(`PR #${prNumber} has ${approvals.length} approval(s) from code owners.`);
