name: Apply Branch Protection

on:
  push:
    branches:
      - main  # Adjust according to your needs
  pull_request:  # If you want it to trigger on PRs
    branches:
      - main

jobs:
  apply_protection_rules:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Apply Branch Protection Rules
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        BRANCH: main
        REVIEWERS: "pathania25, ravicharan-nettyam, manasa-telus"
      run: |
        python3 apply_branch_protection.py
      
  restrict_prod_deployment:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
    - name: Check if it's a production deploy
      run: echo "Production deployment is restricted to the main branch."