name: Enforce Branch Protection

on:
  push:
    branches:
      - main

jobs:
  apply-branch-protection:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Apply Branch Protection
        run: |
          python ./scripts/set_branch_protection.py  # Assuming your Python script is in this path
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}  # Set this secret in GitHub
          REPO_OWNER: ${{ secrets.REPO_OWNER }}
          REPO_NAME: ${{ secrets.REPO_NAME }}
