name: Example Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Use Secret in Script
        run: |
          echo "Running a script with a secret environment variable"
          echo "TOKEN_GITHUB is: ${{ secrets.TOKEN_GITHUB }}"
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}  # Use the secret as an environment variable
