name: Setup GitHub Settings

on:
  push:
    branches:
      - main  # Trigger this workflow on pushes to the main branch

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install requests library
        run: pip install requests

      - name: Use Composite Action to Setup Settings
        uses: ./.github/actions/setup-settings
