name: Protect Main Branch
on:
  push:
    branches:
      - main
jobs:
  no-direct-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check for Direct Push to Main
        run: |
          if [ "${{ github.event_name }}" = "push" ] && [ "${{ github.ref }}" = "refs/heads/main" ]; then
            echo "Direct push to main is not allowed. Please use a pull request.";
            exit 1;
          fi
  
