name: Setup PR Approvers (Ravi and Manasa)

on:
  pull_request:
    branches:
      - '*'  # Trigger on any branch

jobs:
  setup-codeowners:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create or Update CODEOWNERS
        run: |
          # Check if the CODEOWNERS file already exists
          if [ ! -f .github/CODEOWNERS ]; then
            echo "CODEOWNERS file does not exist. Creating one..."
            echo "* @pathania25 @ravicharan-nettyam @manasa-telus" > .github/CODEOWNERS
          else
            echo "Updating existing CODEOWNERS file."
            echo "* @pathania25 @ravicharan-nettyam @manasa-telus" > .github/CODEOWNERS
          fi

      - name: Commit and Push Changes
        run: |
          # Configure Git
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

          # Add, commit, and push changes
          git add .github/CODEOWNERS
          git commit -m "Add/Update CODEOWNERS for Ravi and Manasa" || echo "No changes to commit"
          git push origin ${{ github.head_ref }}